name: time_money
description: Time Money App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: 3.7.5

dependencies:
  bloc: ^8.1.1
  build_runner: ^2.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  provider: ^6.0.5
  dartz: ^0.10.1
  objectbox: ^1.7.2
  objectbox_flutter_libs: ^1.7.2
  flutter_web_plugins:
    sdk: flutter
  path_provider: ^2.0.13
  path: ^1.8.2
  flutter_hooks: ^0.18.6

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  objectbox_generator: ^1.7.2
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
