name: time_money
description: Time Money App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  bloc: ^9.2.0
  collection: ^1.18.0
  drift: ^2.32.0
  drift_flutter: ^0.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  meta: ^1.15.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  intl: ^0.20.0
  json_annotation: ^4.8.0
  fpdart: ^1.2.0
  objectbox: ^5.2.0
  objectbox_flutter_libs: ^5.2.0
  flutter_web_plugins:
    sdk: flutter
  path_provider: ^2.0.13
  path: ^1.8.2

dev_dependencies:
  bloc_test: ^10.0.0
  drift_dev: ^2.32.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  objectbox_generator: ^5.2.0
  very_good_analysis: ^10.2.0
  freezed: ^3.2.5
  build_runner: ^2.13.1
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  generate: true
