// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/features/times/infraestructure/timebox.dart';
import 'src/features/wage_hourly/infraestructure/wage_hourly_box.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7443704063251689733),
      name: 'TimeBox',
      lastPropertyId: const IdUid(3, 4613111846464606794),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1458660342663906038),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 9220117843141886681),
            name: 'hour',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4613111846464606794),
            name: 'minutes',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 1397771064655685503),
      name: 'WageHourlyBox',
      lastPropertyId: const IdUid(2, 1227875365833965248),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6082580828192077545),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1227875365833965248),
            name: 'value',
            type: 8,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 1397771064655685503),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    TimeBox: EntityDefinition<TimeBox>(
        model: _entities[0],
        toOneRelations: (TimeBox object) => [],
        toManyRelations: (TimeBox object) => {},
        getId: (TimeBox object) => object.id,
        setId: (TimeBox object, int id) {
          object.id = id;
        },
        objectToFB: (TimeBox object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.hour);
          fbb.addInt64(2, object.minutes);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TimeBox(
              hour: const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              minutes:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));

          return object;
        }),
    WageHourlyBox: EntityDefinition<WageHourlyBox>(
        model: _entities[1],
        toOneRelations: (WageHourlyBox object) => [],
        toManyRelations: (WageHourlyBox object) => {},
        getId: (WageHourlyBox object) => object.id,
        setId: (WageHourlyBox object, int id) {
          object.id = id;
        },
        objectToFB: (WageHourlyBox object, fb.Builder fbb) {
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.value);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = WageHourlyBox(
              value:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [TimeBox] entity fields to define ObjectBox queries.
class TimeBox_ {
  /// see [TimeBox.id]
  static final id = QueryIntegerProperty<TimeBox>(_entities[0].properties[0]);

  /// see [TimeBox.hour]
  static final hour = QueryIntegerProperty<TimeBox>(_entities[0].properties[1]);

  /// see [TimeBox.minutes]
  static final minutes =
      QueryIntegerProperty<TimeBox>(_entities[0].properties[2]);
}

/// [WageHourlyBox] entity fields to define ObjectBox queries.
class WageHourlyBox_ {
  /// see [WageHourlyBox.id]
  static final id =
      QueryIntegerProperty<WageHourlyBox>(_entities[1].properties[0]);

  /// see [WageHourlyBox.value]
  static final value =
      QueryDoubleProperty<WageHourlyBox>(_entities[1].properties[1]);
}
